---
- name: Tomcat -javaagent setup
  lineinfile:
    dest: "{{ jvm_conf_file }}"
    line: export CATALINA_OPTS="$CATALINA_OPTS -javaagent:{{ server_root }}/newrelic/newrelic.jar"
    create: yes # the file often doesn't exist with Tomcat
    mode: "0755"
  when: server_type == "tomcat"
  become: yes
  notify:
    - restart web server

- name: Jetty -javaagent setup
  lineinfile:
    dest: "{{ jvm_conf_file }}"
    line: JAVA_OPTIONS="$JAVA_OPTIONS -javaagent:{{ server_root }}/newrelic/newrelic.jar"
    create: no
  when: server_type == "jetty"
  become: yes
  notify:
    - restart web server

- name: Wildfly standalone -javaagent setup
  lineinfile:
    dest: "{{ jvm_conf_file }}"
    line: JAVA_OPTS="$JAVA_OPTS -javaagent:{{ server_root }}/newrelic/newrelic.jar"
    create: no
  when: server_type == "wildfly"
  become: yes
  notify:
    - restart web server

- name: Websphere javaagent script copy
  copy:
    src: "{{ role_path }}/files/addJavaAgentWAS.py"
    dest: "{{ server_root }}/newrelic/addJavaAgentWAS.py"
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
    mode: "0750"
  when: server_type == "websphere"
  become: yes
  register: copyStep

- name: Websphere -javaagent setup with auth
  shell: "{{ server_root }}/bin/wsadmin.sh -conntype {{ wsadmin_conntype | default('SOAP') }} -host {{ wsadmin_host }} -port {{ wsadmin_port }} -user {{ wsadmin_user }} -password {{ wsadmin_password }} -f {{ copyStep.dest }} {{ was_server_name }} {{ server_root }}/newrelic/newrelic.jar"
  when: 
    - server_type == "websphere"
    - wsadmin_auth|default(false)|bool
  become: yes
  register: wsjavaagentscript
  changed_when: "'javaagent already defined' not in wsjavaagentscript.stdout"
  notify: 
    - websphere node sync
    - restart web server

- name: Websphere -javaagent setup without auth
  shell: "{{ server_root }}/bin/wsadmin.sh -f {{ copyStep.dest }} {{ was_server_name }} {{ server_root }}/newrelic/newrelic.jar"
  when: 
    - server_type == "websphere"
    - not wsadmin_auth|default(false)|bool
  become: yes
  register: wsjavaagentscript
  changed_when: "'Added javaagent argument on at least one server' in wsjavaagentscript.stdout"
  notify: 
    - websphere node sync
    - restart web server

- name: Websphere Java2 security WAS 9.x
  blockinfile:
    backup: yes
    path: "{{ was_root }}/java/{{ was_java_version }}/jre/lib/security/java.policy"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ was_server_name }}"
    block: |
      grant codeBase "file:{{ server_root }}/newrelic-" {
       permission java.security.AllPermission;
       permission java.net.NetPermission "specifyStreamHandler";
       permission java.net.SocketPermission "*.newrelic.com", "connect,accept,resolve";
      };
  when: 
    - server_type == "websphere"
    - was_version == "9.x"
    - was_java_security_update|default(false)|bool
  become: yes
  notify: 
    - restart web server

- name: Websphere Java2 security WAS 8.x
  blockinfile:
    backup: yes
    path: "{{ was_root }}/java/jre/lib/security/java.policy"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ was_server_name }}"
    block: |
      grant codeBase "file:{{ server_root }}/newrelic-" {
       permission java.security.AllPermission;
       permission java.net.NetPermission "specifyStreamHandler";
       permission java.net.SocketPermission "*.newrelic.com", "connect,accept,resolve";
      };
  when: 
    - server_type == "websphere"
    - was_version == "8.x"
    - was_java_security_update|default(false)|bool
  become: yes
  notify: 
    - restart web server